### ISSUE TITLE
large amounts of paginated data is not allowed: response status code 422: unprocessable_entity

### ISSUE THREAD

**Issue by mschmieder** [blackducksoftware/bd_export_spdx2.2#13]
Hello,

I'm currently facing the following issue trying to generate a SPDX file for one of our projects.

`
2022-04-19 09:16:32,762:ERROR:GET https://xxx.app.blackduck.com/api/projects/xxxx-b15f-41a2-a2eb-972a5b5f85a8/versions/xxxx-e565-4dd4-8e0b-6043170462ac/components?limit=5000
2022-04-19 09:16:32,762:ERROR:HTTP response status code 422: unprocessable_entity
2022-04-19 09:16:32,763:ERROR:HTTP response json (formatted): {
    "logRef": "hub-webapp_P92S7Biz",
    "errorMessage": "Due to performance constraints, asking for large amounts of paginated data is not allowed",
    "arguments": {},
    "errorCode": "{core.rest.excessive_request}",
    "errors": [],
    "links": []
}
`

**Comment by matthewb66** [comment]
Please confirm the size of the project (number of components).

**Comment by matthewb66** [comment]
This utility was updated to v0.24 on 18 Apr to resolve the issue of API request limits introduced in server v2022.2 and above.

Please confirm you are using the latest version (v0.24)

**Comment by mschmieder** [comment]
Hi Matthew,

The version used is v0.23 as it gets pulled in by pip from pypi.org <http://pypi.org/>. The latest version on pypi.org is v0.23
Please see https://pypi.org/project/bd-export-spdx2.2/ <https://pypi.org/project/bd-export-spdx2.2/>. I also cannot find a v0.24 on GitHub. The latest released version there is also v0.23.
https://github.com/blackducksoftware/bd_export_spdx2.2 <https://github.com/blackducksoftware/bd_export_spdx2.2>




Best,
Matthias

**Comment by matthewb66** [comment]
Apologies - I updated the code but did not create a release.
v0.24 should be fully released now

**Comment by mschmieder** [comment]
@matthewb66 the issue still persists even with `v0.24`. I don't think this can be considered `closed`. See the screenshot attached.

![Screenshot 2022-04-24 at 09 18 42](https://user-images.githubusercontent.com/16526092/164965002-f4cbea9e-d14c-4ec4-8f1e-ecd9cabd294f.png)

The only thing that notably changed is the limit that now seems to be at `1000` instead of `500`

**Comment by matthewb66** [comment]
Hi Matthias

I have validated that the new version works for large projects:

[image: image.png]

I see from the log you have sent that the source line numbers do not agree
with the 0.24 version so you are clearly still running an older version.

The reported script version on the command line is still showing as 0.23
which is a minor issue but the code is updated - I will update to v0.25 to
address this.

Please confirm how you are installing and running the utility.

The recommended method is to install as a pip package:
       pip install --upgrade bd_export_spdx2.2

Then confirm the installed version using 'pip list'.

Then run the utility using:
      bd_export_spdx --blackduck_url URL --blackduck_api_token API PROJ VER

Alternatively you can run using python3:
      python3 bd_export_spdx2.2.py --blackduck_url URL
--blackduck_api_token API PROJ VER

Thanks

**Comment by mschmieder** [comment]
Matthew,

It was my fault, somehow my venv did not work. I did delete the comment again and hopes no one saw it ;)

Everything works as expected! Thanks for your help!

Von meinem iPhone gesendet
